### ISSUE TITLE
Usage of this project

### ISSUE THREAD

**Issue by oudinia** [riccardomariani/odata-v4-ng#1]
Hello, Is this project, ongoing.

is what is implented stable, as I wish to use it for a project going into production on February ?

Thanks.

**Comment by riccardomariani** [comment]
Hi @oudinia,
yes the project is ongoing. I took a pause from working on this project because I've been very busy lately with my job. I had to spend my free time working at my full time job instead of working on this project. Anyway we are going to release the new version of the product in a week or so, so I'll restart working on this project very soon.
The API is stable for v1.0.0. I'm using this library in production in the Company I'm working. 
I didn't change version to v1.0.0 yet because I wanted to add additional unit tests before marking it as really stable. If you will use this library in production and you will find any bug, please open an issue and I'll try to fix it as soon as possible. Anyway any feedback or contribution is very appreciated. 

Thanks for asking.

**Comment by fjdiazt** [comment]
Great new! I will start using this also, and going live around march of this year. I am mostly interested in the batch code, we will use batches extensively. Thank you for your work.

**Comment by riccardomariani** [comment]
Hi @fjdiazt,
I'm glad you will start using this library and thanks for sharing details about the usage you will do of the library so that I concentrate my time testing more that part. As I said previously any feedback or contribution is very appreciated so please open bugs if you find any and feature requests if you need anything new.

Thanks for joining.
